export const experienceConfig = [
  {
    name: "Freelance Developer",
    dateRanges: ["Present"],
    titles: ["Freelance Developer"],
    languages: [
      "JavaScript",
      "jQuery",
      "TypeScript",
      "HTML",
      "CSS",
      "Sass",
      "SQL",
      "C#",
      "PHP",
    ],
    frameworks: [
      "Vuejs(2 - 3)",
      "Reactjs",
      "Nodejs",
      "Concrete5",
      "Laravel",
      "Express",
      "Bootstrap",
      "Adobe Analytics",
      "Google Analytics",
      ".Net",
      "Webpack",
    ],
    databaseManagement: [
      "MySQL",
      "PHPMyAdmin",
      "Microsoft SQL Server",
      "Relational databases (RDBMS)",
    ],
    devOps: [
      "AWS",
      "Digital Ocean",
      "Grafana",
      "Google Anaytics,",
      "Google Tag manager",
      "Adobe Analytics",
      "Docker",
      "Webpack",
      "Git",
      "GitHub",
      "BitBucket",
      "Jira",
      "Storybook",
      "Jest",
      "TestCafe",
      "SonarQube",
      "Jenkins",
      "CI/CD",
      "Windows",
      "Linux",
      "Mac",
    ],
    skills: [
      "Written Communication",
      "UI/UX Experience",
      "Test Automation",
      "Scrum",
      "Scrum master trained",
      "Mentor",
      "Reliable",
      "Planning",
      "OOP",
      "Soft skills",
      "SEO",
      "Marketing",
    ],
    description:
      "As a Free lance developer, all of my skills are available. Do you have a interesting project? Feel free to reachout with details!",
  },
  {
    name: "IHS Markit",
    languages: ["JavaScript", "HTML", "CSS", "Sass", "SQL", "C#"],
    frameworks: [
      "Vuejs(2 - 3)",
      "Reactjs",
      "Nodejs",
      "Express",
      "Bootstrap",
      "Adobe Analytics",
      "Google Analytics",
      ".Net",
    ],
    databaseManagement: [
      "Microsoft SQL Server",
      "Relational databases (RDBMS)",
    ],
    devOps: [
      "AWS",
      "Digital Ocean",
      "Google Anaytics,",
      "Google Tag manager",
      "Adobe Analytics",
      "Docker",
      "Webpack",
      "Git",
      "GitHub",
      "BitBucket",
      "Jira",
      "Storybook",
      "Jest",
      "TestCafe",
      "SonarQube",
      "Jenkins",
      "CI/CD",
      "Windows",
      "Linux",
      "Mac",
    ],
    skills: [
      "Written Communication",
      "UI/UX Experience",
      "Test Automation",
      "Scrum",
      "Scrum master trained",
      "Mentor",
      "Reliable",
      "Planning",
      "OOP",
      "Soft skills",
      "SEO",
      "Marketing",
    ],
    description: "",
  },
  {
    name: "Greenius",
    dateRanges: [],
    titles: [],
    languages: [],
    frameworks: [],
    skills: [],
    description: "",
  },
  {
    name: "Infotech Research Group",
    dateRanges: [],
    titles: [],
    languages: [],
    frameworks: [],
    skills: [],
    description: "",
  },
  {
    name: "ProfitDriver Solutions",
    dateRanges: [],
    titles: [],
    languages: [],
    frameworks: [],
    skills: [],
    description: "",
  },
  {
    name: "Arcane",
    dateRanges: [],
    titles: [],
    languages: [],
    frameworks: [],
    skills: [],
    description: "",
  },
];
