export const experienceConfig = [
  {
    name: "Freelance Developer",
    dateRange: "Present",
    roles: ["Freelance Developer"],
    languages: [
      "JavaScript",
      "jQuery",
      "TypeScript",
      "HTML",
      "CSS",
      "Sass",
      "SQL",
      "C#",
      "PHP",
    ],
    frameworks: [
      "Vuejs(2 - 3)",
      "Reactjs",
      "Nodejs",
      "Concrete5",
      "Laravel",
      "Express",
      "Bootstrap",
      "Adobe Analytics",
      "Google Analytics",
      ".Net",
      "Webpack",
    ],
    databaseManagement: [
      "MySQL",
      "PHPMyAdmin",
      "Microsoft SQL Server",
      "Relational databases (RDBMS)",
    ],
    devOps: [
      "AWS",
      "Digital Ocean",
      "Grafana",
      "Google Anaytics,",
      "Google Tag manager",
      "Adobe Analytics",
      "Docker",
      "Webpack",
      "Git",
      "GitHub",
      "BitBucket",
      "Jira",
      "Storybook",
      "Jest",
      "TestCafe",
      "SonarQube",
      "Jenkins",
      "CI/CD",
      "Windows",
      "Linux",
      "Mac",
    ],
    skills: [
      "Soft skills",
      "Written Communication",
      "UI/UX Experience",
      "Test Automation",
      "Scrum",
      "Scrum master trained",
      "Mentor",
      "Reliable",
      "Planning",
      "OOP",
      "SEO",
      "Marketing",
      "Git",
    ],
    description:
      "As a Free lance developer, all of my skills are available. Do you have a interesting project? Feel free to reachout with details!",
  },
  {
    name: "IHS Markit",
    dateRange: "Aug 2020 - Dec 2024",
    roles: [
      "Support",
      "Scrum master",
      "Accessibility specialist",
      "QA analyst",
      "Software Developer",
      "24/7 Onvsll support",
      "Mentor",
    ],
    languages: ["JavaScript", "HTML", "CSS", "Sass", "SQL", "C#"],
    frameworks: [
      "Vuejs(2 - 3)",
      "Vuex",
      "Reactjs",
      "Nodejs",
      "Express",
      "Bootstrap",
      "Adobe Analytics",
      "Google Analytics",
      ".Net",
    ],
    databaseManagement: [
      "Microsoft SQL Server",
      "Relational databases (RDBMS)",
    ],
    devOps: [
      "Accessibility (WCAG2.1)",
      "Google Anaytics,",
      "Google Tag manager",
      "Adobe Analytics",
      "Postman",
      "Git",
      "BitBucket",
      "Jira",
      "Storybook",
      "Jest",
      "TestCafe",
      "SonarQube",
      "Jenkins",
      "CI/CD",
      "Grafana",
      "Windows",
    ],
    skills: [
      "Soft skills",
      "Written communication",
      "Verbal communication",
      "UI/UX Experience",
      "Test automation",
      "Scrum",
      "Scrum master trained",
      "Documentation",
      "Mentor",
      "Reliable",
      "Planning",
      "SDLC",
      "OOP",
      "Marketing",
      "Git",
    ],
    description: "",
  },
  {
    name: "Greenius",
    dateRange: "Feb 2020 - Apr 2020",
    roles: ["Support", "Senior Software Developer"],
    languages: ["PHP", "HTML", "CSS", "SQL", "Ubuntu", "Nodejs"],
    frameworks: ["Native-php", "PHPMyAdmin", "Google Tag manager"],
    skills: [
      "Soft skills",
      "Written communication",
      "Verbal communication",
      "UI/UX Experience",
      "Documentation",
      "Reliable",
      "Planning",
      "OOP",
      "Marketing",
      "SEO",
      "Google Analytics",
      "Git",
    ],
    description: "",
  },
  {
    name: "Infotech Research Group",
    dateRange: "Nov 2018 - Jan 2020",
    titles: ["Intermediate Software Developer"],
    languages: ["JavaScript", "HTML", "CSS", "Sass", "SQL", "PHP"],
    frameworks: ["Nodejs", "Laravel", "PHPMyAdmin", "PHPUnit"],
    databaseManagement: ["MySQL", "PHPMyAdmin", "Relational databases (RDBMS)"],
    devOps: ["Google Anaytics,", "Google Tag manager", "Git", "Jira", "Mac"],
    skills: [
      "Soft skills",
      "Written Communication",
      "UI/UX Experience",
      "Test Automation",
      "Scrum",
      "Reliable",
      "Planning",
      "OOP",
    ],
    description: "",
  },
  {
    name: "ProfitDriver Solutions",
    dateRange: "Apr 2018 - Oct 2018",
    titles: ["Web developer"],
    languages: ["jQuery", "HTML", "CSS", "Sass", "SQL", "PHP"],
    frameworks: ["Laravel", "Express", "Bootstrap", "Google Analytics"],
    databaseManagement: ["PHPMyAdmin", "Relational databases (RDBMS)"],
    devOps: ["Google Anaytics,", "Google Tag manager", "Git", "Mac"],
    skills: [
      "Soft skills",
      "Written Communication",
      "UI/UX Experience",
      "OOP",
      "Git",
    ],
    description: "",
  },
  {
    name: "Arcane",
    dateRange: "Feb 2014 - Oct 2018 ",
    titles: [
      "Web Developer",
      "Analytics and Quality developer",
      "Conversion Optizmation Manager",
    ],
    languages: ["jQuery", "HTML", "CSS", "Sass", "SQL", "PHP"],
    frameworks: [
      "Nodejs",
      "Concrete5",
      "WordPress",
      "Laravel",
      "Adobe Analytics",
      "Google Analytics",
      "Various social platform analytics",
    ],
    databaseManagement: ["MySQL", "PHPMyAdmin", "Relational databases (RDBMS)"],
    devOps: [
      "AWS",
      "Digital Ocean",
      "Google Tag manager",
      "Docker",
      "Webpack",
      "Git",
      "Jira",
      "CI/CD",
      "Mac",
      "Linux",
      "Ubuntu",
    ],
    skills: [
      "Soft skills",
      "Client softskills",
      "Written Communication",
      "UI/UX Experience",
      "Test Automation",
      "Scrum",
      "Planning",
      "OOP",
      "SEO",
      "Marketing",
      "Git",
      "Management",
    ],
    description: "",
  },
];
